const catFacts = [
  "Cats can make over 100 different sounds.",
  "A group of cats is called a clowder.",
  "Cats spend about 70% of their lives sleeping.",
  "Cats have a special organ that allows them to 'taste' scents.",
  "Every cat's nose print is unique, much like a human fingerprint.",
  "Cats can jump up to six times their length.",
  "A cat's hearing is much more acute than a human's.",
  "Cats have a third eyelid called the nictitating membrane.",
  "Most cats are lactose intolerant.",
  "Cats use their whiskers to navigate in the dark.",
  "Cats can rotate their ears 180 degrees.",
  "A cat's brain is similar to a human's in terms of structure.",
  "Cats have five toes on their front paws and four on their back paws.",
  "Some cats are polydactyl, meaning they have more than the usual number of toes.",
  "The first cat in space was French (Félicette).",
  "Cats can run up to 30 mph.",
  "A cat's purr frequency can help improve bone density and heal tendons.",
  "Most cats only meow at humans, not other cats.",
  "Cats have a powerful sense of balance thanks to their inner ear.",
  "Ancient Egyptians worshipped cats as symbols of grace and protection.",
  "Some cats are allergic to certain plants like lilies.",
  "A cat's heart beats 110 to 140 times per minute.",
  "Cats can't taste sweetness.",
  "A cat's tongue is rough because of tiny spines called papillae.",
  "Cats can see in light six times weaker than humans need.",
  "The oldest known pet cat was found in a 9,500-year-old grave on Cyprus.",
  "Cats can't see directly under their nose.",
  "Cats dream just like humans do.",
  "Cats have scent glands on their cheeks, paws, and tail.",
  "A cat's whiskers are as wide as its body.",
  "Cats can walk without putting all four paws down at once.",
  "Cats can recognize their owner's voice but pretend not to.",
  "A cat's eyes can't focus underwater.",
  "The world's largest cat measured 48.5 inches long.",
  "A cat's stomach is only about the size of a walnut.",
  "A cat's kneading behavior comes from kittenhood nursing.",
  "Cats have 20 different muscles controlling each ear.",
  "The most popular cat name worldwide is Luna.",
  "Cats can't bark, but there's a barking cat breed.",
  "A cat's eyes are three times more sensitive to light than human eyes.",
  "Cats have a special reflex where they arch their back when startled.",
  "A cat's eyes open the moment it is born.",
  "Cats can change their meow pitch to manipulate humans.",
  "The domestic cat is the only pet not descended from a wild species.",
  "Cats sweat through the pads of their paws.",
  "A cat can spend 12 to 16 hours a day sleeping.",
  "Cats have a higher pain tolerance than most animals.",
  "A cat's tail is used for communication and balance.",
  "Cats can detect pheromones from other cats.",
  "The first cartoon cat was Felix, created in 1919.",
  "Cats have a wider field of vision than humans at 200 degrees.",
  "A cat's jaw cannot move sideways.",
  "Cats were banned in France during the Black Death because they were thought to be witches.",
  "A cat can absorb vitamin D from sunlight through its skin.",
  "Cats have a special collarbone that helps them land on their feet.",
  "The average cat has 230 bones, more than humans.",
  "Cats can smell well enough to detect illness in their owners.",
  "A kitten's eyes turn blue within days of birth.",
  "Cats have been domesticated for about 10,000 years.",
  "A cat's memory lasts three times longer than a dog's.",
  "Cats have a unique walking style called pacing.",
  "The fastest domestic cat can reach 48 km/h.",
  "Cats can walk on all fours without all paws touching the ground simultaneously.",
  "A cat's nose is designed to pick up scents better than humans.",
  "Cats have a higher blood pressure than humans.",
  "The Russian Blue breed has green eyes and silver fur.",
  "Cats can be left-handed or right-pawed.",
  "A cat's purr can reach frequencies between 25 and 150 Hertz.",
  "Cats have over 130 recognized breeds worldwide.",
  "Cats can't see the color red.",
  "A cat's ears have 32 muscles each.",
  "Cats have a natural instinct to bury their waste.",
  "A cat's vocal cords can produce a sound called chirping.",
  "Cats have a higher metabolic rate than dogs.",
  "The Siamese cat was once considered sacred in Thailand.",
  "Cats can detect subtle changes in human emotions.",
  "A cat's nose can distinguish over 200 different scents.",
  "Cats have a natural fear of cucumbers due to their snake-like appearance.",
  "A cat's whiskers help it determine if it can fit through a space.",
  "Cats have a special bone in their ear called the stylohyoid.",
  "The Persian cat is one of the oldest known breeds.",
  "Cats can hear ultrasonic frequencies that humans cannot.",
  "A cat's eyes reflect green, gold, or blue in the dark.",
  "Cats have a natural ability to self-medicate with certain plants.",
  "A cat's kneading is called making biscuits.",
  "Cats can live up to 20 years with proper care.",
  "A cat's tail position reveals its mood.",
  "Cats have a stronger immune system than most mammals.",
  "The Maine Coon is the largest domesticated cat breed.",
  "Cats can rotate their ears independently.",
  "A cat's nose pad is used for scent marking.",
  "Cats have a natural instinct to climb high places.",
  "A cat's saliva has antibacterial properties.",
  "Cats can sense weather changes before they happen.",
  "The average domestic cat weighs between 8 to 10 pounds.",
  "Cats have a natural reflex to groom themselves after eating.",
  "A cat's eyes are positioned to give excellent depth perception.",
  "Cats can survive falls from great heights due to their righting reflex.",
  "A cat's favorite temperature range is between 80 to 86 degrees Fahrenheit.",
  "Cats have been depicted in art for thousands of years.",
  "Cats can produce over 15 types of vocalizations.",
  "A cat's eyes contain 200,000 rods per square millimeter for night vision.",
  "Cats were considered sacred by the Vikings and traveled with them on ships.",
  "A cat's brain is 90% similar to a human brain.",
  "Cats have a unique ability to slow their heart rate when resting.",
];

const floatingCats = document.querySelectorAll(".floating-cats span");

if (floatingCats.length > 0) {
  const shuffledFacts = [...catFacts].sort(() => Math.random() - 0.5);
  let factIndex = 0;

  floatingCats.forEach((cat) => {
    cat.style.left = `${Math.random() * 95}%`;
    cat.style.top = `${Math.random() * 95}vh`;

    const myFact = shuffledFacts[factIndex % shuffledFacts.length];
    factIndex++;

    cat.addEventListener("click", () => {
      alert(`Cat Fact: ${myFact}`);
    });
    cat.style.cursor = "pointer";
  });
}
